name: run_tracker
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #IMPORT LIBRARIES
  shared_preferences: ^2.0.5
  toast: ^0.1.5
  permission_handler: any
  syncfusion_flutter_gauges: ^19.2.46
  google_maps_flutter: ^0.5.30
  location: ^3.0.2
  geolocator: ^4.0.3
  flutter_polyline_points: ^0.1.0
  pedometer: ^3.0.0
  lottie: ^0.6.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 600
        - asset: fonts/Roboto-Black.ttf
          weight: 700


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/icons/
   - assets/icons/ic_back.png
   - assets/icons/ic_person_walk.png
   - assets/icons/ic_person_run.png
   - assets/icons/ic_footstep.png
   - assets/icons/ic_waterdrops.png
   - assets/icons/ic_steps.png
   - assets/icons/ic_water.png
   - assets/icons/ic_route_map.png
   - assets/icons/ic_best_pace.png
   - assets/icons/ic_distance.png
   - assets/icons/ic_duration.png
   - assets/icons/ic_male.png
   - assets/icons/ic_info_white.png
   - assets/icons/ic_female.png
   - assets/icons/ic_select_pointer.png
   - assets/icons/ic_setalite.png
   - assets/icons/ic_person_bottombar.png
   - assets/icons/ic_map_permission.png
   - assets/images/
   - assets/images/dummy_girl.png
   - assets/images/bg_countdown_timer_blue.webp
   - assets/images/bg_countdown_timer_green.webp
   - assets/animation/
   - assets/animation/countdown_blue.json
   - assets/animation/countdown_green.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
